import React, { useState, useEffect, useContext } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import axios from "axios";
import { useRouter } from "next/router";
import Cookies from "js-cookie";
import { toast } from "react-toastify";
import { useForm, Controller } from "react-hook-form";

// material
import { styled } from "@mui/styles";
import { Card, Stack, Container, Typography } from "@mui/material";

import RegisterForm from "../components/auth/RegisterForm";
import AuthSocial from "../components/auth/AuthSocial";
import { Store } from "../utils/Store";

const SectionStyle = styled(Card)(() => ({
  width: "100%",
  maxWidth: 464,
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  margin: "2 0 2 2",
}));

const ContentStyle = styled("div")(() => ({
  maxWidth: 480,
  margin: "auto",
  display: "flex",
  minHeight: "100vh",
  flexDirection: "column",
  justifyContent: "center",
  padding: "12 0",
}));

const register = () => {
  const {
    handleSubmit,
    control,
    formState: { errors },
  } = useForm();

  const { state, dispatch } = useContext(Store);
  const { userInfo } = state;
  const router = useRouter();
  const { redirect } = router.query;

  const [loading, setLoading] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [name, setName] = useState("");
  const [confirmedPassword, setConfirmedPassword] = useState("");

  useEffect(() => {
    if (userInfo) {
      router.push("/");
    }
  }, []);

  const submitHandler = async ({
    name,
    email,
    password,
    confirmedPassword,
  }) => {
    setLoading(true);
    try {
      if (password !== confirmedPassword) {
        toast.warning("Password don't match");
        setLoading(false);
        return;
      }
      const { data } = await axios.post("/api/auth/register", {
        name,
        email,
        password,
      });
      dispatch({ type: "USER_LOGIN", payload: data });
      Cookies.set("userInfo", data);

      router.push(redirect || "/");

      toast.success("successfully register");
      setLoading(false);
    } catch (error) {
      toast.error("Register Failed");
      setLoading(false);
    }
  };

  return (
    <div
      style={{ display: "flex" }}
      className="mt-10 ml-6 mr-6 md:ml-10 md:mr-10"
    >
      <Head>
        <title>Register | Ecommerce Myanmar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <MHidden width="mdDown"> */}
      <SectionStyle>
        <Typography variant="h3" sx={{ px: 5, mt: 10, mb: 5 }}>
          Shopping Around
        </Typography>
        <Image
          src="/images/illustrations/illustration_register.png"
          width="400"
          height="350"
          alt="register"
        />
      </SectionStyle>
      {/* </MHidden> */}

      <Container maxWidth="sm">
        <ContentStyle>
          <Stack sx={{ mb: 5 }}>
            <Typography variant="h4" gutterBottom>
              Register with your email
            </Typography>
            <Typography sx={{ color: "text.secondary" }}>....</Typography>
          </Stack>
          <AuthSocial />

          <RegisterForm
            name={name}
            setName={setName}
            confirmedPassword={confirmedPassword}
            setConfirmedPassword={setConfirmedPassword}
            submitHandler={submitHandler}
            Controller={Controller}
            handleSubmit={handleSubmit}
            loading={loading}
            showPassword={showPassword}
            setShowPassword={setShowPassword}
            control={control}
            errors={errors}
          />

          <Typography variant="body2" align="center" sx={{ mt: 3 }}>
            Already have an account?&nbsp;
            <span className="text-green-500">
              <Link href="/login">Login</Link>
            </span>
          </Typography>
        </ContentStyle>
      </Container>
    </div>
  );
};

export default register;
